### ISSUE TITLE
Option to disable TERMCOLOR

### ISSUE THREAD

**Issue by nigelbabu** [loadtheaccumulator/glusto#7]
The colors make the entire log difficult to read on a browser. Inevitably, that's where you read it after running the tests on Jenkins.

**Comment by loadtheaccumulator** [comment]
Fixed in v0.54. Adding log_color: False to the /etc/glusto/default.yml file will disable it for all /usr/bin/glusto runs, or for individual runs you can add it to any of the config files you load at the command-line via glusto -c "config_file". You can also set it via code with g.config['log_color'] = False. I had this in the default config file and some doc, but did not commit that patch with the logic--until now. I'll update docs in the next patch.

On a separate note, we're using the ansicolor jenkins plug-in, but it only works with output to the console log and not workspace files. Looking into whether that's pluggable in Jenkins.
